// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHy58oOVG-agecUbniPKeD-CAOk_EGv30',
    appId: '1:407238634628:web:7df9a0fa80fb8e9458e6d1',
    messagingSenderId: '407238634628',
    projectId: 'first-project--health-connect',
    authDomain: 'first-project--health-connect.firebaseapp.com',
    storageBucket: 'first-project--health-connect.appspot.com',
    measurementId: 'G-2VS38BH1F8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-61dsiR0fH7rlIw1ebaR2Y1kXP64qVuU',
    appId: '1:407238634628:android:953949ed66cfc20f58e6d1',
    messagingSenderId: '407238634628',
    projectId: 'first-project--health-connect',
    storageBucket: 'first-project--health-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYbEFSSKWdddT2G31e6PdktL4nxrYGg5E',
    appId: '1:407238634628:ios:a0bc32e060dae1be58e6d1',
    messagingSenderId: '407238634628',
    projectId: 'first-project--health-connect',
    storageBucket: 'first-project--health-connect.appspot.com',
    iosClientId: '407238634628-b4ssr5kubvhskhdr7mqf7ggmvk1ueajm.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthConnectNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYbEFSSKWdddT2G31e6PdktL4nxrYGg5E',
    appId: '1:407238634628:ios:a0bc32e060dae1be58e6d1',
    messagingSenderId: '407238634628',
    projectId: 'first-project--health-connect',
    storageBucket: 'first-project--health-connect.appspot.com',
    iosClientId: '407238634628-b4ssr5kubvhskhdr7mqf7ggmvk1ueajm.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthConnectNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHy58oOVG-agecUbniPKeD-CAOk_EGv30',
    appId: '1:407238634628:web:60b14ec5caea72ba58e6d1',
    messagingSenderId: '407238634628',
    projectId: 'first-project--health-connect',
    authDomain: 'first-project--health-connect.firebaseapp.com',
    storageBucket: 'first-project--health-connect.appspot.com',
    measurementId: 'G-4ZD65550H4',
  );
}
